package org.maequise.hibernate.profiler.core.annotations;

/// Indicates that a test method is subject to control any insert query generated by the Hibernate ORM
/// It must be used in conjunction with the [org.junit.jupiter.api.Test] annotation
///
/// The annotation can be combined by other tool annotation:
///
/// - [SelectQuery]
/// - [UpdateQuery]
///
/// ```java
///     @Test
///     @InsertQuery
///     void testQuery() {
///     }
/// ```
///
/// In the previous sample we assume that the test should not perform any insert query, otherwise an [org.opentest4j.AssertionFailedError] will be thrown

public @interface DeleteQuery {
    /// Total of update queries expected
    /// By default none is expected
    int totalExpected() default 0;

    /// Indicate the exact update query that is performed
    String queryExpected() default "";
}
