package org.maequise.hibernate.profiler.core.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/// Indicates that a test method is subject to control any `select` query generated by the Hibernate ORM
/// It must be used in conjunction with the [org.junit.jupiter.api.Test] annotation
///
/// The annotation can be combined by other tool annotation:
///
/// - [ExpectedInsertQuery]
/// - [ExpectedUpdateQuery]
///
/// ```java
///     @Test
///     @SelectQuery
///     void testQuery() {
///     }
/// ```
///
/// In the previous sample we assume that the test should not perform any select query, otherwise an [org.opentest4j.AssertionFailedError] will be thrown
///
/// In some case, and depending on the `database` used, a select query can be performed to get the generated id
/// to prevent this such case use the annotation with the [ExpectedSelectQuery#excludeSequenceQueries()]
///
/// @author maequise
/// @since 0.1.0
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface ExpectedSelectQuery {
    /// Indicate the number of select queries are expected
    /// By default 0 no select query is expected
    int value() default 0;

    /// Indicate which query is expected during the select operation
    String queryExpected() default "";

    /// Pass to true if a middle query is performed to get the next ID for the entity to persist
    /// By default at false
    boolean excludeSequenceQueries() default false;
}
