package org.maequise.hibernate.profiler.core.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/// Indicates that a test method is subject to control any `update` query generated by the Hibernate ORM
/// It must be used in conjunction with the [org.junit.jupiter.api.Test] annotation
///
/// The annotation can be combined by other tool annotation:
///
/// - [ExpectedInsertQuery]
/// - [ExpectedSelectQuery]
///
/// ```java
///     @Test
///     @UpdateQuery
///     void testQuery() {
///     }
/// ```
///
/// In the previous sample we assume that the test should not perform any update query, otherwise an [org.opentest4j.AssertionFailedError] will be thrown
///
/// @author maequise
/// @since 0.1.0
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD})
public @interface ExpectedUpdateQuery {
    /// Total of update queries expected
    /// By default none is expected
    int value() default 0;

    /// Indicate the exact update query that is performed
    String queryExpected() default "";
}
