package org.maequise.hibernate.profiler.core.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/// Indicates that a test method is subject to control any insert query generated by the Hibernate ORM
/// It must be used in conjunction with the [org.junit.jupiter.api.Test] annotation
///
/// The annotation can be combined by other tool annotation:
///
/// - [SelectQuery]
/// - [UpdateQuery]
///
/// ```java
///     @Test
///     @InsertQuery
///     void testQuery() {
///     }
/// ```
///
/// In the previous sample we assume that the test should not perform any insert query, otherwise an [org.opentest4j.AssertionFailedError] will be thrown

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface InsertQuery {
    /// Define the number of `insert` query expected, by default `0`
    int totalExpected() default 0;

    /// Define que exact query expected
    String queryExpected() default "";
}
